website/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns =[

    path('',views.content_list,name='blog_list'),
    path('artigos/<int:content_id>/<slug:slug>/',views.content_detail, name='content_detail'),
    path('email_list',views.email_list,name='email_list'),




]

website/finance/urls.py
from django.urls import path
from . import views


app_name = 'finance'
#<slug:slug>/<int:week_days>/
urlpatterns = [

	path('checkout1/<int:course_choice>/', views.checkout1,name='checkout1'),	
	path('check_prices/',views.check_prices,name='check_prices'),
	path('checkout3/<int:package>/',views.checkout3,name='checkout3')


]

website/website/urls.py
from django.contrib import admin
from django.urls import path,include
from blog import urls,views
from accounts import urls
from plataforma import urls
from finance import urls
admin.autodiscover()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('plataforma/',include('plataforma.urls')),
    path('finance/',include('finance.urls')),
    path('',views.index,name='index'),
 
]

website/finance/models.py
from django.db import models

website/finance/views.py
from django.shortcuts import render,redirect
from accounts.models import Teacher
from django.contrib.auth.decorators import login_required
import datetime



'''
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    is_student = models.BooleanField(default=False)
    email_token = models.IntegerField(default=0)
    email_status = models.BooleanField(default=False)
    class_time = models.CharField(max_length=500)  
    teacher = models.CharField(max_length=500)    
 '''
@login_required(login_url='/accounts/login_user/') 
def checkout1(request,course_choice):
	if request.method == 'POST':
		user = request.user
		teacher_id = request.POST['teacher_id']
		time_hour = request.POST['time_selected1']
		time_day = request.POST['timeday1']
		teacher = Teacher.objects.get(pk=teacher_id)
		user.profile.teacher = teacher.name
		now = datetime.datetime.now()
		user.profile.class_time = str(now) + " - " + time_day + " - " + time_hour
		user.save()
		payment = False
		message = "A sua mensagem foi salva no nosso sistema. Enviaremos um email respondendo em breve."
		context = {'message':message,'payment':payment}				
		return render(request,'finance/checkout2.html',context)
	else:
		teachers = Teacher.objects.all()
		if course_choice == 1:
			message = False
		else:
			message = True
		context = {'teachers':teachers,'message':message}
		return render(request,'finance/checkout1.html',context)

@login_required(login_url='/accounts/login_user/') 
def checkout3(request,package):
	if package == 1:
		message = True
		course = 'Assinante Premium Zero To Hero English'
	else:
		message = False
		course = 'Assinante Zero To Hero English'
	context = {'message':message,'course':course}
	return render(request,'finance/checkout3.html',context)

@login_required(login_url='/accounts/login_user/') 
def check_prices(request):
	return render(request,'finance/prices.html')

website/finance/templates/finance/checkout1.html
{% extends 'blog/base.html' %}


{% block content %}
<style type="text/css">
	.margin-bottom{
		margin-bottom: 20px;
	}
  .bold{
    font-weight: bold;
  }
  .site-color{
    color:#339af0;
  }
  .border-top{
    border-top:solid 1px #339af0;
  }
  .shadow:hover {
    -moz-box-shadow:    inset 0 0 10px #000000;
   -webkit-box-shadow: inset 0 0 10px #000000;
   box-shadow:         inset 0 0 10px #000000;
  }

</style>

<!--breadcrumb-->
    <nav  aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="">Home</a></li>            
            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'finance:check_prices' %}">Produtos e Preços</a></li>
            <li class="breadcrumb-item">Pagamento</li>
        </ol>
    </nav>

<div class="container">
<!--Fazer incrição para que seja possível selecionar horário-->

{% if user.is_active %}


<div class="row">

<div class="col-md-4 col-lg-4">
<div class="card-deck mb-3 text-center">
        <div class="shadow card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Aulas Particulares - 4 aulas/mês</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title"><span class="site-color" >R$ 200 </span></h1>
                        
                        
          </div>
        </div>
</div>
<div class="card-deck mb-3 text-center">
        <div class="shadow card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Aulas Particulares - 8 aulas/mês</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title"><span class="site-color" >R$ 380 </span></h1>                        
            </div>
        </div>
</div>
<div class="card-deck mb-3 text-center">
        <div class="shadow card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Aulas Particulares - 12 aulas/mês</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title"><span class="site-color" >R$ 570 </span></h1>                        
            </div>
        </div>
</div>
<div class="card-deck mb-3 text-center">
        <div class="shadow card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Opções personalizadas</h4>
          </div>
          <div class="card-body">
             <small > Para mais aulas por mês ou alguma quantidade diferente de aulas, escreva quais são suas necessidades no espaço ao lado, abaixo do professor escolhido. Enviaremos um e-mail logo em seguida.</small>                      
            </div>
        </div>
</div>

</div>







<div class="col-md-8 col-lg-8">


<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Professores e Horários:</h1>
    <p class="lead">Escreva os melhores horários para você ter aulas no campo abaixo do professor escolhido. Exemplo: Terças e Quintas - Noite.</p>
    <p class="lead">Enviaremos um email para marcarmos a aula experimental e aulas seguintes, além das opções de pagamento.</p>
    <p class="lead">Prefere nos contatar por whatsapp? Mande uma mensagem para (19) 984186413.</p>
  </div>
</div>
{% for teacher in teachers %}
           <div class="card">
                    <div class="card-header">
                              <small class="bold-text text-muted">{{teacher.name}}</small>
                    </div>
                    <div class="row">
                          <div class="padding-4px text-center col-lg-2 card-body">
                              <small class="bold-text text-muted"><p class="card-text">{{post.author.name}}</p></small>
                              <img src="{{teacher.img}}" width="80" height="80" alt="Imagem do Autor" class="rounded-circle">
                          </div>
                          <div class="top-paddin-5px col-lg-10">
                                <small class="text-muted">{{teacher.description}} </small>
                          </div>
                    </div>
                

                
                


            <form action="{% url 'finance:checkout1' 1 %}" method="POST">{% csrf_token %}

                                      
                           <input type="hidden" name="teacher_id" value="{{teacher.id}}">
                           <input type="hidden" name="timeday1" value="{{time.day}}">
                         
                           <div class="form-group">
                              <label for="exampleFormControlTextarea1">Escreva os seus horários disponíveis e clique em enviar mensagem.</label>
                              <textarea class="form-control"  name="time_selected1" id="hour" rows="3"></textarea>
                          </div>
                                             
                            
          
            <input class="btn btn-primary" type="submit" value="Enviar mensagem">
            </form>
             
            
              </div>

{% endfor %}
 </div>




<!--Botão de pagamento-->

 





{% else %}



  <div class="card-body">
    <div class="margin-bottom text-center">
        <h5 class="card-title">Informações do Estudante</h5>
         <p class="card-text">Faça um cadastro no nosso site, assim você poderá escolher o horário da aula experimental e efetuar pagamentos.</p>
    
    </div>
      <div>{% include 'registration/create_user_form.html' %}</div>
  	 
  </div>
  {% endif %}

</div>
</div>
</div>

{% endblock %}

website/finance/templates/finance/checkout2.html
{% extends 'blog/base.html' %}


{% block content %}
<style type="text/css">
	.margin-bottom{
		margin-bottom: 20px;
	}
    .margin-bottom{
    margin-bottom: 20px;
  }
  .bold{
    font-weight: bold;
  }
  .site-color{
    color:#339af0;
  }
  .border-top{
    border-top:solid 1px #339af0;
  }
  .shadow:hover {
    -moz-box-shadow:    inset 0 0 10px #000000;
   -webkit-box-shadow: inset 0 0 10px #000000;
   box-shadow:         inset 0 0 10px #000000;
  }

</style>


<!--breadcrumb-->
    <nav  aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="">Home</a></li>            
            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'finance:check_prices' %}">Produtos e Preços</a></li>
            <li class="breadcrumb-item">Pagamento</li>
        </ol>
    </nav>
<div class="container">


{% if user.is_active %}

 {% if payment %}

 <div class="row">
<div class="col-md-4 col-lg-4">
<div class="card-deck mb-3 text-center">
        <div class="shadow card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Aulas Particulares - 4 aulas/mês</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title"><span class="site-color" >R$ 200 </span></h1>
                        
                        
          </div>
        </div>
</div>
<div class="card-deck mb-3 text-center">
        <div class="shadow card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Aulas Particulares - 8 aulas/mês</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title"><span class="site-color" >R$ 380 </span></h1>                        
            </div>
        </div>
</div>
<div class="card-deck mb-3 text-center">
        <div class="shadow card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Aulas Particulares - 12 aulas/mês</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title"><span class="site-color" >R$ 570 </span></h1>                        
            </div>
        </div>
</div>
<div class="card-deck mb-3 text-center">
        <div class="shadow card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Opções personalizadas</h4>
          </div>
          <div class="card-body">
             <small > Para mais aulas por mês ou alguma quantidade diferente de aulas, escreva quais são suas necessidades no espaço ao lado, abaixo do professor escolhido. Enviaremos um e-mail logo em seguida.</small>                      
            </div>
        </div>
</div>

</div>

<div class="col-md-8 col-lg-8">




<div class="card">
  <div class="card-header">
    Pagamento
  </div>
  <div class="card-body">
    <h5 class="card-title">Olá {{user.username}}</h5>
    <p class="card-text">{{message}}</p>
    <p>Você terá aulas com o professor(a) {{user.profile.teacher}}.</p></p>
     

</div>

</div>
</div>
</div>
</div>

   {% else %}



<div class="row">
<div class="col-md-4 col-lg-4">
<div class="card-deck mb-3 text-center">
        <div class="shadow card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Aulas Particulares - 4 aulas/mês</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title"><span class="site-color" >R$ 200 </span></h1>
                        
                        
          </div>
        </div>
</div>
<div class="card-deck mb-3 text-center">
        <div class="shadow card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Aulas Particulares - 8 aulas/mês</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title"><span class="site-color" >R$ 380 </span></h1>                        
            </div>
        </div>
</div>
<div class="card-deck mb-3 text-center">
        <div class="shadow card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Aulas Particulares - 12 aulas/mês</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title"><span class="site-color" >R$ 570 </span></h1>                        
            </div>
        </div>
</div>
<div class="card-deck mb-3 text-center">
        <div class="shadow card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Opções personalizadas</h4>
          </div>
          <div class="card-body">
             <small > Para mais aulas por mês ou alguma quantidade diferente de aulas, escreva quais são suas necessidades no espaço ao lado, abaixo do professor escolhido. Enviaremos um e-mail logo em seguida.</small>                      
            </div>
        </div>
</div>

</div>

<div class="col-md-8 col-lg-8">
<div class="card">
  <div class="card-header">
    Pagamento
  </div>
  <div class="card-body">
    <h5 class="card-title">Olá {{user.username}}</h5>
    <p class="card-text">{{message}}</p>
    <p>Você terá aulas com o professor(a) {{user.profile.teacher}}.</p></p>


     
  </div>
</div>
</div>

</div>

{% endif %}

<!--Botão de pagamento-->

 
{% else %}
 <div class="card-body">
    <div class="margin-bottom text-center">
    <h5 class="card-title">Informações do Estudante</h5>
    <p class="card-text">Faça um cadastro no nosso site, assim você poderá escolher o horário da aula experimental e efetuar pagamentos.</p>
    
    </div>
    <div>{% include 'registration/create_user_form.html' %}</div>
  	 
  </div>
  {% endif %}

</div>
{% endblock %}

website/finance/templates/finance/checkout3.html
{% extends 'blog/base.html' %}


{% block content %}
<style type="text/css">
	.margin-bottom{
		margin-bottom: 20px;
      .margin-bottom{
    margin-bottom: 20px;
  }
  .bold{
    font-weight: bold;
  }
  .site-color{
    color:#339af0;
  }
  .border-top{
    border-top:solid 1px #339af0;
  }
  .shadow:hover {
    -moz-box-shadow:    inset 0 0 10px #000000;
   -webkit-box-shadow: inset 0 0 10px #000000;
   box-shadow:         inset 0 0 10px #000000;
  }
	}

</style>
<!--breadcrumb-->
    <nav  aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="">Home</a></li>            
            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'finance:check_prices' %}">Produtos e Preços</a></li>
            <li class="breadcrumb-item">Pagamento</li>
        </ol>
    </nav>
<div class="container">
<div class="container">
<!-- receber professores e listar nomes e horários -->
{% if message %}

<div class="row"> 

  <div class="col-md-4 col-lg-4">
    
<div class="shadow card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Assinante Zero To Hero Englishs</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title"><span class="site-color">R$ 99,99</span> <small class="text-muted">/ mês</small></h1>
            
            <ul class="list-unstyled mt-3 mb-4">
              <small ><li class="border-top">Acesso aos podcasts semanais com scripts</li></small>
              <small > <li class="border-top">Materiais lançados semanalmente com exercícios</li></small>
              <small ><li class="border-top">Acesso a plataforma</li></small>
              <small > <li class="border-top">Acesso as aulas semanais</li></small>
              <small > <li class="border-top">Materiais necessários: Grátis</li></small>
              <small > <li class="border-top">Fórum de dúvidas</li></small>
              <small > <li class="border-top">Uma aula particular por mês - 50 minutos</li></small>
              <small > <li class="border-top"><li>Curso do básico ao intermediário/avançado</li></small>
              <small > <li class="border-top"><li>Duração de 6 meses - Todo o material fica disponível 24h por dia</li></small>
            </ul>          


  </div>
</div>
</div>
<div class="col-md-8 col-lg-8">
<div class="card">
  <div class="card-header">
    Pagamento
  </div>
  <div class="card-body">
    <h5 class="card-title">Olá {{user.username}}</h5>
    <p class="card-text">{{course}}</p>
    <p class="card-text">Para obter a sua assinatura click no botão abaixo.</p>
    
    
                    
<a mp-mode="dftl" href="http://mpago.la/R3E7" name="MP-payButton" class='lightBlue-ar-l-rn-undefined'>Assinar</a>
<script type="text/javascript">
    (function() {
        function $MPC_load() {
            window.$MPC_loaded !== true && (function() {
                var s = document.createElement("script");
                s.type = "text/javascript";
                s.async = true;
                s.src = document.location.protocol + "//secure.mlstatic.com/mptools/render.js";
                var x = document.getElementsByTagName('script')[0];
                x.parentNode.insertBefore(s, x);
                window.$MPC_loaded = true;
            })();
        }
        window.$MPC_loaded !== true ? (window.attachEvent ? window.attachEvent('onload', $MPC_load) : window.addEventListener('load', $MPC_load, false)) : null;
    })();
</script>

                
   
                    


                

  </div>
</div>
</div>


 {% else %}

<div class="row">
  <div class="col-md-4 col-lg-4">
    
<div class="shadow card mb-4 box-shadow">
          <div class="card-header">            <h4 class="my-0 font-weight-normal">Estudante Zero To Hero English</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title"><span class="site-color" >R$ 49,99</span> <small class="text-muted">/ mês</small></h1>
             
            <ul class="list-unstyled mt-3 mb-4">
              <small ><li class="border-top">Acesso aos podcasts semanais com scripts</li></small>
              <small > <li class="border-top">Materiais lançados semanalmente</li></small>
              <small ><li class="border-top">Acesso a plataforma</li></small>
              <small ><li class="border-top">Fórum de dúvidas</li></small>              
            </ul>
            <h5>Você não terá:</h5>
            <ul class="list-unstyled mt-3 mb-4">
              <small class="risk text-muted"><li class="border-top"><strike>Acesso as aulas semanais</strike></li></small>
              <small class="risk text-muted"> <li class="border-top"><strike>Uma aula particular por mês - 50 minutos</strike></li></small>
                           
            </ul>



           
          </div>
        </div>

    
  </div>
  <div class="ol-md-8 col-lg-8">

<div class="card">
  <div class="card-header">
    Pagamento
  </div>
  <div class="card-body">
    <h5 class="card-title">Olá {{user.username}}</h5>
    <p class="card-text">{{course}}</p>
    <p class="card-text">Para obter a sua assinatura click no botão abaixo.</p>
    
    
                    
<a mp-mode="dftl" href="http://mpago.la/85QD" name="MP-payButton" class='lightBlue-ar-l-rn-undefined'>Assinar</a>
<script type="text/javascript">
    (function() {
        function $MPC_load() {
            window.$MPC_loaded !== true && (function() {
                var s = document.createElement("script");
                s.type = "text/javascript";
                s.async = true;
                s.src = document.location.protocol + "//secure.mlstatic.com/mptools/render.js";
                var x = document.getElementsByTagName('script')[0];
                x.parentNode.insertBefore(s, x);
                window.$MPC_loaded = true;
            })();
        }
        window.$MPC_loaded !== true ? (window.attachEvent ? window.attachEvent('onload', $MPC_load) : window.addEventListener('load', $MPC_load, false)) : null;
    })();
</script>

                
   
                    


                

  </div>

   </div>
   </div>
   </div>










<!--Botão de pagamento-->
  {% endif %}
 

{% endblock %}

website/finance/templates/finance/price_base.html
<div class="container">
      <div class="card-deck mb-3 text-center">
      
        <div class="shadow card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Assinante Zero To Hero English</h4>
          </div>
          <div class="card-body">
            <h3 class="card-title pricing-card-title"><span class="site-color" >Ainda não disponível</span> <small class="text-muted"></small></h3>
             <a {% comment %}href="{% url 'finance:checkout3' 1 %} {%endcomment%}"><button  type="button" class="margin-top btn btn-primary">Assinar Curso</button></a>
            <ul class="list-unstyled mt-3 mb-4">
              <small ><li class="border-top">Acesso aos podcasts semanais com scripts</li></small>
              <small > <li class="border-top">Materiais lançados semanalmente com exercícios</li></small>
              <small ><li class="border-top">Acesso a plataforma</li></small>
              <small > <li class="border-top">Acesso as aulas semanais</li></small>
              <small > <li class="border-top">Materiais necessários: Grátis</li></small>
              <small > <li class="border-top">Fórum de dúvidas</li></small>
              <small > <li class="border-top">Uma aula particular por mês - 50 minutos</li></small>
              <small > <li class="border-top"><li>Curso do básico ao intermediário/avançado</li></small>
              <small > <li class="border-top"><li>Duração de 6 meses - Todo o material fica disponível 24h por dia</li></small>
            </ul>
           
          </div>
        </div>

          <div class="shadow card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Aulas Particulares</h4>
          </div>
           <div class="card-body">
            <h1 class="card-title pricing-card-title">Aulas <span class="site-color" >personalizadas</span> </h1>
           
           <a href="{% url 'finance:checkout1' 1 %} "><button  type="button" class="margin-top btn btn-primary">Ver Opções e Preços</button></a>
           

            <ul class="list-unstyled mt-3 mb-4">
              <small ><li class="border-top">Uma aula experimental grátis</li></small>
              <small ><li class="border-top">Atendimento personalizado</li></small>
              <small ><li class="border-top ">Acesso aos podcasts semanais com scripts</li></small>
              <small ><li class="border-top">Correção de exercícios,tarefas e textos</li></small>
              <small > <li class="border-top">Aulas com duração de 1 hora</li></small>
              <small > <li class="border-top">Materiais necessários: Grátis</li></small>
              <small > <li class="border-top">Acesso a plataforma</li></small>
              <small > <li class="border-top">Pacote renovado a cada mês, sem contrato de fidelidade</li></small>
              <small > <li class="border-top">É necessário ter skype</li></small>
              
              <small class="bold text-muted"><li></li></small>
            </ul>
            
          </div>
        </div>
        <div class="shadow card mb-4 box-shadow">
          <div class="card-header">            <h4 class="my-0 font-weight-normal">Cursos De Inglês Completos</h4>
          </div>
          <div class="card-body">
            <h3 class="card-title pricing-card-title"><span class="site-color" >Ainda não disponível</span> <small class="text-muted"></small></h3>
             <a><button  type="button" class="margin-top btn btn-primary">Assinar </button></a>
            <ul class="list-unstyled mt-3 mb-4">
              <small ><li class="border-top">Acesso aos podcasts semanais com scripts</li></small>
              <small ><li class="border-top">Curso completo de inglês</li></small>
              <small > <li class="border-top">Materiais lançados semanalmente</li></small>
              <small ><li class="border-top">Acesso a plataforma</li></small>
              <small ><li class="border-top">Fórum de dúvidas</li></small>              
            </ul>
           


           
          </div>
        </div>
      </div>

website/finance/templates/finance/prices.html
{% extends 'blog/base.html' %}


{% block content %}
<style type="text/css">
	
	.bold{
		font-weight: bold;
	}
	.site-color{
		color:#339af0;
	}
	.border-top{
		border-top:solid 1px #339af0;
	}
	.shadow:hover {
    -moz-box-shadow:    inset 0 0 10px #000000;
   -webkit-box-shadow: inset 0 0 10px #000000;
   box-shadow:         inset 0 0 10px #000000;
	}


</style>

<!--breadcrumb-->
    <nav  aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Produtos e Preços</li>
        </ol>
    </nav>
<div class="container">
     

     {% include "finance/price_base.html" %}
      </div>

{% endblock %}

website/finance/templates/finance/week_table.html
{% extends 'blog/base.html' %}


{% block content %}


{% endblock %}