website/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('create_account/',views.create_user,name='create_user'),
    path('login_user/',views.login_user,name='login_user'),
    path('logout_user/',views.logout_user, name='logout_user'),
    path('number_token_form/',views.number_token_form,name='number_token_form'),
    path('email_confirm_done/',views.email_confirm_done,name='email_confirm_done'),
    path('email_confirm_fail/',views.email_confirm_fail,name='email_confirm_fail'),
    
    

]

website/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns =[

    path('',views.content_list,name='blog_list'),
    path('artigos/<int:content_id>/<slug:slug>/',views.content_detail, name='content_detail'),
    path('email_list',views.email_list,name='email_list'),




]

website/plataforma/urls.py
from django.urls import path
from plataforma import views

app_name = 'plataforma'

urlpatterns = [	
	path('',views.plataforma_index,name='plataforma_index'),
	path('course_content/<int:course_id>/<slug:slug>/',views.course_content,name='course_content'),
	path('topic_content/<slug:course_link>/<int:topic_id>/<slug:slug>/',views.topic_content, name='topic_content'),
	path('quiz/<int:topic_id>/<slug:slug>/',views.quiz, name='quiz'),
	path('word_list/',views.word_list,name="word_list"),
	path('user_page/',views.user_page,name="user_page"),
	
]

website/website/urls.py
from django.contrib import admin
from django.urls import path,include
from blog import urls,views
from accounts import urls
from plataforma import urls
from finance import urls
admin.autodiscover()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('plataforma/',include('plataforma.urls')),
    path('finance/',include('finance.urls')),
    path('',views.index,name='index'),
 
]

website/blog/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=100)
    img = models.URLField(blank=True)
    description = models.TextField()

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=500)
    accesses_number = models.IntegerField(default=0)
    seo_url_do_post = models.SlugField(max_length=500)
    img_post = models.URLField()
    thumbnail_post = models.TextField()
    keywords = models.CharField(max_length=1000)
    content = models.TextField()
    pub_date = models.DateField()
    author = models.ForeignKey(Author,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Email(models.Model):
    email = models.CharField(max_length=500,blank=True)

    def __str__(self):
        return self.email

website/blog/views.py
from django.shortcuts import render
from .models import Post,Email
from django.http import HttpResponse

#Receive Ajax Data from post comments and subcomments

def index(request):
    return render(request,'blog/index.html')


#return the blog's list of posts
def content_list(request):        
    posts = Post.objects.order_by('-pub_date')  
    context = {'posts':posts}     
    return render(request, 'blog/content_list.html', context)

#return post detail, list of posts and lists of popular posts
def content_detail(request,content_id,slug):
    if request.method == 'POST':
        email = request.POST['email']
        e = Email(email=email)
        e.save()  
    content = Post.objects.get(pk=content_id)
    post_list = Post.objects.order_by('-pub_date')
    popular_posts = Post.objects.order_by('accesses_number')
    context = {'post':content,'post_list':post_list,'popular_posts':popular_posts}
    content.accesses_number +=1
    content.save()
    return render(request, 'blog/content_detail.html',context)

def email_list(request):
    emails = Email.objects.all()    
    context = {'emails':emails} 
    return render(request, 'blog/email_list.html', context) 

website/blog/templates/blog/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
     {% block extra_head_content %}{% endblock %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
   <style type="text/css">
     #white{
      color:white;
     }




.countdown {
  float: left;
  margin-top: 5px;
}

.countdown--digit {
  font-size: 2.5em;
  font-weight: bold;
  background-color: #ffda00;
  padding: 5px;
  width: 80px;
  text-align: center;
  display: inline-block;
  border-radius: 4px;
  margin: 5px 3px 0 0;
}

.countdown--unit {
  font-size: 0.37em;
  font-weight: 100;
  color: #ffffff;
  background-color: #000000;
}
    
   </style>

    </head>
  <body>
   

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

              <a class="navbar-brand" href="{% url 'index' %}">
                <img src="{% static 'blog/images/logo1.png' %}" width="126" height="48" alt="">               
              </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="move-right navbar-nav mr-auto">
                      <li class="nav-item">
                        <a id="white" class="nav-link " href="{% url 'index' %}">Home</a>
                      </li>
                      <li class="nav-item">
                        <a  id="white" class="nav-link" href="{% url 'blog:blog_list' %}">Blog</a>
                      </li>
                      <li class="nav-item">
                        <a  id="white" class="nav-link" href="{% url 'plataforma:plataforma_index' %}">Plataforma</a>
                      </li>                      
                  </ul>
                  <ul class="navbar-nav ml-auto">

                  {% if user.is_authenticated %}

                      

                      <li class="nav-item">
                        <a  id="white" class="nav-link">Olá {{user.username}}</a>
                      </li>

                      {% if user.is_staff %}

                      <li class="nav-item">
                        <a  href="{% url 'blog:email_list' %}"  id="white" class="nav-link">Lista de emails</a>
                      </li>

                      {% endif %}

                      <li class="nav-item">
                        <a href="{% url 'plataforma:user_page' %}" id="white" class="nav-link">Meu Perfil</a>
                      </li>

                      <li class="nav-item">
                        <a href="{% url 'plataforma:word_list' %}" id="white" class="nav-link">Palavras do dia</a>
                      </li>
                      
                      <li class="nav-item">
                        <a  id="white" class="nav-link" href="{% url 'accounts:logout_user' %}">Sair</a>
                      </li>

                      {% else %}
                  <form action="{% url 'accounts:login_user' %}"class="form-inline my-2 my-lg-0" method="POST">
                    {% csrf_token %}
                      <input class="margin-top form-control mr-sm-2" name="username" type="text" placeholder="Nome de usuário" aria-label="Nome de usuário" required>
                      <input class="margin-top form-control mr-sm-2" name="password" type="password" placeholder="Senha" aria-label="Nome de usuário" required>
                      <button  id="white" class="margin-top btn btn-primary"  type="submit">Entrar</button>
                  </form>
                  {% endif %}
              </div>
            </ul>

      </nav>




        {% block content %}
        {% endblock %}




    <!--timer -->

    <!-- Include TimeR default stylesheet -->
<link href="css/default-style.css" rel="stylesheet">

<!-- Create a container for the TimeR to insert into -->
<div id="TimeR"></div>

<!-- Create a container for the date of the countdown to insert into -->
<div id="until"></div>

<!-- Include the Moment library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.js"></script>

<!-- Include the TimeR library -->
<script src="js/TimeR-2.0.1.js"></script>

<!-- Initialize TimeR countDown -->
<script type="text/javascript">
  window.addEventListener("load", function() {

    var t = new TimeR({
      id     : "TimeR",
      now    : "02/18/2017 8:00:00",
      end    : "03/17/2017 1:00:00",

      unitNames : {
        "minutes": "MINS", //End with Plural
        "seconds": "SECS",
        "years"  : "YEARS",
        "days"   : "DAYS",
        "hours"  : "HOURS"
      }

    });

    t.countDown();


  });
</script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.js"></script>

    <!-- Bootstrap javascript,jequery etc. -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'blog/js/main.js' %}"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

website/blog/templates/blog/content_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}{{post.title|title}}{% endblock %}
{% block extra_head_content %}
<meta name="description" content="{{post.thumbnail_post}}"/>
<meta name="keywords" content="{{post.keywords}}"/>
<meta name="author" content="{{post.author}}"/>

{% endblock %}


{% block javascript %}
<script type="text/javascript">
  function revealForm(forloop_id){
    document.getElementById("subcommentForm"+forloop_id).style.display = "block";
    document.getElementById("answerbutton"+forloop_id).style.display="none";
  }
</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v3.1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


{% endblock %}




{% block content %}

<style type="text/css">
   .bottom-margin{
          margin-bottom: 20px;
      }

  
</style>

<!--breadcrumb-->
    <nav  aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a  href="{% url 'index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'blog:blog_list' %}">Blog</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{post.title|title}}</li>
        </ol>
    </nav>

<div class="">



<div class="container">

<div class="row">
<!--Post detail-->
<div class="col-sm-12 col-md-9 col-lg-9">
      <h1>{{post.title|title}}</h1>
      <small class="text-muted">{{post.pub_date}} by  {{post.author}}</small>

      <div class="top-space-30px text-justify">
      <p>{{post.content|safe}}</p>
      </div>
<!--Author details-->
                <div class="card">
                    <div class="card-header">
                              <small class="bold-text text-muted">Autor</small>
                    </div>
                    <div class="row">
                          <div class="padding-4px text-center col-lg-2 card-body">
                              <small class="bold-text text-muted"><p class="card-text">{{post.author.name}}</p></small>
                              <img src="{{post.author.img}}" width="80" height="80" alt="Imagem do Autor" class="rounded-circle">
                          </div>
                          <div class="top-paddin-5px col-lg-10">
                                <small class="text-muted">{{post.author.description}} </small>
                          </div>
                    </div>

                </div>

<!-- Comments Form -->
<div id="disqus_thread"></div>
<script>
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { 
var d = document, s = d.createElement('script');
s.src = 'https://zerotoheroenglish.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>
     
<!--Side posts indication-->
<div class="col-sm-12 col-md-3 col-lg-3">

  <form class="bottom-margin" action="{% url 'blog:content_detail' post.id post.seo_url_do_post %}" method="POST">
         {% csrf_token %}
  <div class="form-group">
    <h3>Gostaria de receber posts em seu email? Increva-se.</h3>
    <input type="email" name="email" class="form-control" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">Não compartilharemos o seu email com ninguém.</small>
  </div>
    <button type="submit" class="btn btn-primary">Salvar Email na Lista</button>
</form>

<!--facebook plugin page-->  <div class="fb-page" data-href="https://www.facebook.com/Zero-to-Hero-English-240962006631552/" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/Zero-to-Hero-English-240962006631552/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/Zero-to-Hero-English-240962006631552/">Zero to Hero English</a></blockquote></div>

  <h4 class="top-margin-space-20px text-center">Artigos Populares</h4>
  {% for indPost in popular_posts reversed %}
      {% if indPost.id == post.id %}
      {% else %}
      {% if forloop.counter <= 4 %}
      <div class="top-margin-space-20px content-box card">
          <div class="card-body">
            <a href="{% url 'blog:content_detail' indPost.id indPost.seo_url_do_post %}"><h5 class="card-title">{{indPost.title|title|truncatewords:8}}</h5></a>
            <p class="card-text"><small class="text-muted"></small></p>
          </div>
          <img class="card-img-bottom" src="{{indPost.img_post}}" alt="{{indPost.title}}">
      </div>
      {% endif %}
      {% endif %}
      
    {% endfor %}
</div>
</div>







<!--Container Div end-->
</div>


{% endblock %}

website/blog/templates/blog/content_list.html
{% extends 'blog/base.html' %}
{% block title %}Blog Zero To Hero English{% endblock %}
{% block content %}
  <style>
    .top-container{
      position: relative;
      top:50px;

    }
    .content-list{
      position:relative;
      top:80px;

    }
    .titulo-blog-azul{
      color:#007bff;
    }
      .content-box{
          margin-bottom: 15px;
          border:1px solid #cecece;
      }
     
  

  </style>



    <!--breadcrumb-->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a  href="{% url 'index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'blog:blog_list' %}">Blog</a></li>
            <li class="breadcrumb-item active" aria-current="page">Posts</li>
        </ol>
    </nav>
<div class="top-container container">
  <h1 class="text-center">Blog <span class="titulo-blog-azul">Zero</span> To <span class="titulo-blog-azul">Hero</span> English</h1>
  <p class="text-center lead">Materiais, técnicas e dicas de estudo</p>
</div>


<div class="content-list">
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-8">
      {% for post in posts %}
          <div class="content-box card">
              <img class="img-fluid" src="{{post.img_post}}"alt="{{post.title}}">
              <div class="card-body">
                  <a href="{% url 'blog:content_detail' post.id post.seo_url_do_post %}"><h5 class="card-title">{{post.title|title}}</h5></a>
                  <p class="card-text"> {{post.thumbnail_post}}</p>
                  <p class="card-text"><small class="text-muted">{{post.author}} {{post.pub_date}}</small></p>
              </div>
          </div>
          {% empty %}

          <p>Ainda não há posts</p>

        {% endfor %}
    </div>

    <div class="col-sm-12 col-md-12 col-lg-4">


      



      {% for post in posts reversed %}
          <div class="content-box card">
              <div class="card-body">
                <a href="{% url 'blog:content_detail' post.id post.seo_url_do_post %}"><h5 class="card-title">{{post.title|title}}</h5></a>
                <p class="card-text">{{post.thumbnail_post|truncatewords:10}}</p>
                <p class="card-text"><small class="text-muted"></small></p>
              </div>
              <img class="card-img-bottom" src="{{post.img_post}}" alt="{{post.title}}">
          </div>
        {% endfor %}

    </div>

  </div>
</div>
</div>











{% endblock %}

website/blog/templates/blog/email_list.html
{% extends 'blog/base.html' %}


{% block content %}

 <nav  aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a  href="{% url 'index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'blog:blog_list' %}">Blog</a></li>
            <li class="breadcrumb-item active" aria-current="page">Lista de emails</li>
        </ol>
    </nav>

<div class="container">

  {% if user.is_staff %}
 <p>
  {% for email in emails %}
    {{email}};
  {% endfor %}
</p>

{% else %}

<p>Você não tem permissões para acessar essa página.</p>
  {% endif %}
</div>

{% endblock %}

website/blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<style type="text/css">
  
.top-margin{
  margin-top: 50px;
}
.site-color{
    color:#339af0;
  }
.index-intro{
  width:100%;
  background-color: #f3f3f3;
}
.index-intro .jumbotron{
  padding: 100px 6px;
  margin:0px;

}

</style>



    <main role="main">
     <!-- 
      <div id="myCarousel" class="carousel slide" data-ride="carousel">        
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'blog/images/banner.jpg' %}" width="1350" height="482" alt="First slide">
            <div class="container">              
              <div class="carousel-caption text-left ">
                <div class="col-lg-7 text-center">
                <p><img class="first-slide" src="{% static 'blog/images/logo.png' %}" width="126" height="48" alt="First slide"></p>
                </div>
                <h3>Aprenda Inglês Online</h3>
                <p>A Zero To Hero English deixa o seu aprendizado<br>de inglês mais rápido e eficiente.<br>
                Tenha acesso a podcasts em inglês com scripts, professores <br> particulares, vídeos explicativos e muito mais.</p>
                <p><a class="btn btn-lg btn-warning" href="#prices" role="button">Inscreva-se</a></p>
              </div>
            </div>
          </div>          
        </div>        
      </div>
-->

<article class="index-intro">
<div class="container">
  <div class="jumbotron">
    
   


    <div class="row">
          <div class="col-xl-9 mx-auto">
            <h1 class="mb-5">Build a landing page for your business or project and generate more leads!</h1>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <form>
              <div class="form-row">
                <div class="col-12 col-md-9 mb-2 mb-md-0">
                  <input type="email" class="form-control form-control-lg" placeholder="Enter your email...">
                </div>
                <div class="col-12 col-md-3">
                  <button type="submit" class="btn btn-block btn-lg btn-primary">Sign up!</button>
                </div>
              </div>
            </form>
          </div>
        </div>







</div>
</article>


      <!-- Marketing messaging and featurettes
      ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

      <div class="container marketing">
        


        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">Podcasts em inglês <span style="color:#007bff;">com scripts.</span></h2>
            <p class="lead">Tenha podcasts semanais para que você possa praticar a escuta do inglês, você também terá textos explicativos e exercícios sobre tudo que ouviu para máximo aproveitamento.</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" src="{% static 'blog/images/headphones.jpg' %}" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading"> Professores Particulares <span style="color:#007bff;">. Aulas Personalizadas.</span></h2>
            <p class="lead">Professores com aulas online personalizadas para que você seja atendido por nós com aquilo que realmente precisa.</p>
          </div>
          <div class="col-md-5 order-md-1">
            <img class="featurette-image img-fluid mx-auto" src="{% static 'blog/images/laptop.jpg' %}" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">Plataforma de estudos. <span style="color:#007bff;">24 horas por dia.</span></h2>
            <p class="lead">Na plataforma Zero To Hero English você terá vídeos explicativos, lista de exercícios, espaço para tirar todas as suas dúvidas e correção dos seus textos e vídeos em inglês.</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" src="{% static 'blog/images/videos.png' %}" alt="Generic placeholder image">
          </div>
        </div>

        <div class="top-margin" id="prices">

       {% include 'finance/price_base.html' %}

       </div>

        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->

      </div><!-- /.container -->


      <!-- FOOTER -->
      <footer class="container">
        <p class="float-right"><a href="#">Ir para o topo</a></p>
        <p>&copy; 2018 Zero To Hero English</p>
      </footer>
    </main>
{% endblock %}