website/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns =[

    path('',views.content_list,name='blog_list'),
    path('artigos/<int:content_id>/<slug:slug>/',views.content_detail, name='content_detail'),
    path('email_list',views.email_list,name='email_list'),




]

website/plataforma/urls.py
from django.urls import path
from plataforma import views

app_name = 'plataforma'

urlpatterns = [	
	path('',views.plataforma_index,name='plataforma_index'),
	path('course_content/<int:course_id>/<slug:slug>/',views.course_content,name='course_content'),
	path('topic_content/<slug:course_link>/<int:topic_id>/<slug:slug>/',views.topic_content, name='topic_content'),
	path('quiz/<int:topic_id>/<slug:slug>/',views.quiz, name='quiz'),
	path('word_list/',views.word_list,name="word_list"),
	path('user_page/',views.user_page,name="user_page"),
	
]

website/website/urls.py
from django.contrib import admin
from django.urls import path,include
from blog import urls,views
from accounts import urls
from plataforma import urls
from finance import urls
admin.autodiscover()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('plataforma/',include('plataforma.urls')),
    path('finance/',include('finance.urls')),
    path('',views.index,name='index'),
 
]

website/plataforma/models.py
from django.db import models

class Course(models.Model):
	course_title = models.CharField(max_length=300)
	link = models.SlugField(max_length=500)
	status = models.CharField(max_length=200)
	image = models.URLField(max_length=500)

	def __str__(self):
		return self.course_title

class Category(models.Model):
	course = models.ForeignKey(Course,on_delete=models.CASCADE)
	category_title = models.CharField(max_length=300)
	category_number = models.IntegerField()

	def __str__(self):
		return self.category_title

class Topic(models.Model):
	category = models.ForeignKey(Category,on_delete=models.CASCADE)
	topic_title = models.CharField(max_length=500)
	link = models.SlugField(max_length=500)
	content = models.TextField()

	def __str__(self):
		return self.topic_title

class Question(models.Model):
	topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
	question_number = models.IntegerField()
	question_text = models.CharField(max_length=500)
	right_option = models.CharField(max_length=500)
	option1 = models.CharField(max_length=500)
	option2 = models.CharField(max_length=500)
	option3 = models.CharField(max_length=500)
	option4 = models.CharField(max_length=500)
	option5 = models.CharField(max_length=500)

	def __str__(self):
		return self.topic.topic_title + " - " + self.question_text

class Word_list(models.Model):
	list_name = models.CharField(max_length=200)
	list_date = models.DateField()
	list_content = models.TextField()

	def __str__(self):
		return self.list_name

website/plataforma/views.py
from django.shortcuts import render,redirect
from .models import Course,Category,Topic,Word_list
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test

def is_student(user):
    return user.profile.is_student == True

@login_required(login_url='/accounts/login_user/')      
@user_passes_test(is_student,login_url='/finance/check_prices/')
def plataforma_index(request):
    courses = Course.objects.order_by('id')
    context = {'courses':courses}  
    return render(request,'plataforma/plataforma_index.html',context)

@login_required(login_url='/accounts/login_user/')      
@user_passes_test(is_student,login_url='/finance/checkout1/')#redirect to checkout page
def course_content(request,course_id,slug):
	course = Course.objects.get(pk=course_id)
	context = {'course':course}
	return render(request, 'plataforma/course_content.html',context)

@login_required(login_url='/accounts/login_user/')      
@user_passes_test(is_student)#redirect to checkout page
def topic_content(request,course_link,topic_id, slug):
	topic = Topic.objects.get(pk=topic_id)
	context = {'topic':topic}
	return render(request,'plataforma/topic_content.html',context)
    
@login_required(login_url='/accounts/login_user/')      
@user_passes_test(is_student,login_url='/finance/check_prices/')#redirect to checkout page
def quiz(request,topic_id,slug):
    if request.method == 'POST':
        topic = Topic.objects.get(pk=topic_id)
        question_list = topic.question_set.all()
        i=1
        corrects = []
        incorrects = []
        for question in question_list:
            selected_option = request.POST['option{}'.format(i)]
            if question.right_option == selected_option:
                corrects.append(question)
            else:
                incorrects.append(question)
            i+=1
        percentage = float(len(corrects)/(i-1)*100)
        if percentage == 0:
            message = 'Você errou todas as questões, estude o conteúdo novamente e depois disso faça o questionário de novo.'
        elif percentage < 70.0:
            message = 'Você acertou menos de 70 %, reveja o conteúdo, pratique mais e volte a esse questionário para melhorar o seu resultado.'
        elif percentage == 100.0:
            message = 'Parabéns! Um ótimo resultado, continue assim!'
        elif percentage >= 70.0:
            message = 'Muito bem! Você ainda pode melhorar, mas o seu desempenho já está muito bom.'
        
        context = {'corrects':corrects,'incorrects':incorrects,'topic':topic,'percentage':percentage,'message':message}
        return render(request,'plataforma/quiz_result.html',context)
    else:
        topic = Topic.objects.get(pk=topic_id)
        context = {'topic':topic}
        return render(request,'plataforma/quiz.html',context)

@login_required(login_url='/accounts/login_user/')      
@user_passes_test(is_student,login_url='/finance/check_prices/')#redirect to checkout page
def word_list(request):
    word_lists = Word_list.objects.order_by('list_date')
    context = {'word_lists':word_lists}
    return render(request,'plataforma/word_list.html', context)

@login_required(login_url='/accounts/login_user/')      
@user_passes_test(is_student,login_url='/finance/check_prices/')#redirect to checkout page
def user_page(request):
    return render(request,'plataforma/user_page.html')
    

website/plataforma/templates/plataforma/course_content.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
	
	.black-color{
		color:black;
	}
	.bold{
		font-weight: bold;
	}
  .left-margin{
    margin-left: 5px;
  }
</style>

 <nav aria-label="breadcrumb">
  
        <ol class="breadcrumb">

            <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'plataforma:plataforma_index' %}">Plataforma</a></li>
            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'plataforma:plataforma_index' %}">Cursos Zero To Hero English</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{course.course_title|title}}</li>
        </ol>
  
 </nav>
 <div class="container">
<div class="jumbotron jumbotron-fluid">
  		<div class="container">
    		<h1 class="display-4">{{course.course_title}}</h1>
    	</div>
</div>

{% for category in course.category_set.all %}

<div>
  <div class="card">
    <div data-toggle="collapse" data-target="#collapse{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne" class="" id="headingOne">
       <h5 class="mb-{{forloop.counter}}">
        <img class="left-margin" data-toggle="collapse" data-target="#collapse{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne" src="{% static 'plataforma/images/list.svg' %}"/>
        <button class="bold black-color btn btn-link" type="button" data-toggle="collapse" data-target="#collapse{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne">
          {{category.category_number}}.<span class="left-margin">{{category.category_title|title}}</span>
        </button>
      </h5>
    </div>

    <div id="collapse{{forloop.counter}}" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
      {% for topic in category.topic_set.all %}
      <div class="border card-body">        
		{{category.category_number}}.{{forloop.counter}} - <a class="black-color" href="{% url 'plataforma:topic_content' course.link topic.id topic.link %}">{{topic.topic_title|title}}</a>		
      </div>
      {% endfor %}
    </div>
  </div>  
</div>	
	
{% empty %}
<p>Estamos trabalhando nisso e logo teremos conteúdo nessa página.</p>
{% endfor %}
</div>
{% endblock %}

website/plataforma/templates/plataforma/plataforma_index.html
{% extends 'blog/base.html' %}


{% block content %}



 <nav class="" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a  href="{% url 'index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'blog:blog_list' %}">Plataforma</a></li>
            <li class="breadcrumb-item active" aria-current="page">Cursos</li>
        </ol>
 </nav>
<div class="container">
<div class="row">
{% for course in courses %}
<div class="card" style="width: 18rem;margin-left: 20px;">
  <img class="card-img-top" src="{{course.image}}" alt="{{course.course_title}}">
  <div class="card-body">
    <h5 class="card-title">{{course.course_title|title}}</h5>
    <p class="card-text">{{course.status|title}}</p>
    <a href="{% url 'plataforma:course_content' course.id course.link %}" class="btn btn-primary">Ir para o curso</a>
  </div>
</div>
{% endfor %}
</div>
</div>
{% endblock %}

website/plataforma/templates/plataforma/quiz.html
{% extends 'blog/base.html' %}


{% block content %}

<nav class="" aria-label="breadcrumb">
         <ol class="breadcrumb">
            <li class="breadcrumb-item"><a  href="{% url 'index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'plataforma:plataforma_index' %}">Plataforma</a></li>
            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'plataforma:course_content' topic.category.course.id topic.category.course.link %}">{{topic.category.course.course_title|title}}</a></li>
            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'plataforma:topic_content' topic.category.course.link topic.id topic.link %}">{{topic.topic_title|title}}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Quiz</li>

        </ol>
 </nav>
<style type="text/css">
	.list-group-item:hover{
		background-color: #339af0;
	}
	.margin{
		margin:15px;
	}
  .margin-top{
    margin-top: 30px; 
  }

</style>
{% block javascript %}
	<script type="text/javascript">

	</script>
{% endblock %}

<div class="container">

{{topic.title}}

    <form class="" action="{% url 'plataforma:quiz' topic.id topic.link %}" method="POST">
      	{% csrf_token %}
    {% for question in topic.question_set.all %}


  <div class="margin-top card">
  <h5 class="card-header">Questão {{question.question_number}}</h5>
  <div class="card-body">
    <p class="card-text">{{question.question_text}}</p>
    <ul class="list-group">
   	  <label for="id1{{question.question_number}}"><li  class="list-group-item"><input type="radio" id="id1{{question.question_number}}" name="option{{question.question_number}}" value="{{question.option1}}" required>&nbsp{{question.option1}}</li></label>

      <label for="id2{{question.question_number}}"><li  class="list-group-item"><input type="radio" id="id2{{question.question_number}}" name="option{{question.question_number}}" value="{{question.option2}}"required>&nbsp{{question.option2}}</li></label>

      <label for="id3{{question.question_number}}"><li class="list-group-item"><input type="radio" id="id3{{question.question_number}}" name="option{{question.question_number}}" value="{{question.option3}}"required>&nbsp{{question.option3}}</li></label>

      <label for="id4{{question.question_number}}"><li  class="list-group-item"><input type="radio" id="id4{{question.question_number}}" name="option{{question.question_number}}" value="{{question.option4}}"required>&nbsp{{question.option4}}</li></label>

      <label for="id5{{question.question_number}}"><li  class="list-group-item"><input type="radio" id="id5{{question.question_number}}" name="option{{question.question_number}}" value="{{question.option5}}"required>&nbsp{{question.option5}}</li></label>
   </ul>

   
	</div>
</div>
 

    {% endfor %}
     <input class="margin btn btn-primary" type="submit" name="" value="Responder Quiz">
</form>
</div>

{% endblock %}

website/plataforma/templates/plataforma/quiz_result.html
{% extends 'blog/base.html' %}


{% block content %}
<style type="text/css">	
  .margin-top{
    margin-top: 30px; 
  }

</style>

<nav class="" aria-label="breadcrumb">
         <ol class="breadcrumb">
            <li class="breadcrumb-item"><a  href="{% url 'index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'plataforma:plataforma_index' %}">Plataforma</a></li>
            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'plataforma:course_content' topic.category.course.id topic.category.course.link %}">{{topic.category.course.course_title|title}}</a></li>
            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'plataforma:topic_content' topic.category.course.link topic.id topic.link %}">{{topic.topic_title|title}}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Quiz</li>

        </ol>
 </nav>

 {% if error_message %}

 {{error_message}}

 {% else %}



<div class="container">

<div class="card text-center">
  <div class="card-header">
    Esses são seus resultados no quiz sobre "{{topic.topic_title}}"
  </div>
  <div class="card-body">
    <h5 class="card-title">{{message}}</h5>
    {% if percentage >= 70 %}
    <p style="color:#339af0;font-weight: bold;" class="card-text">Você acertou {{percentage}} % do teste!</p>
    {% else %}
    <p style="color:red;font-weight: bold;" class="card-text">Você acertou {{percentage}} % do teste!</p>
    {% endif %}
  </div>
  
</div>

<div class="display-none-incorrect margin-top card">
{% for question in incorrects %}
{% if forloop.counter == 1 %}
<h5 class="card-header">Você errou:</h5>
{% endif %}
<div class="card">
  <h5 class="card-header">Questão {{question.question_number}}</h5>
  <div class="card-body">
    <p class="card-text">{{question.question_text}}</p> 
    <p>A resposta correta é: {{question.right_option}}</p>    
 </div>
</div>
{% empty %}
	<style>
		.display-none-incorrect{
			display: none;
		}
	</style> 
{% endfor %}
</div>


  


<div class="display-none-correct margin-top card">
{% for question in corrects %}
{% if forloop.counter == 1 %}
<h5 class="card-header">Você acertou:</h5>
{% endif %}
<div class="card-background-color card">
  <h5 class="card-header">Questão {{question.question_number}}</h5>
  <div class="card-body">
    <p class="card-text">{{question.question_text}}</p> 
    <p>A resposta correta é: {{question.right_option}}</p>   
 </div>
</div>
{% empty %}
	<style>
		.display-none-correct{
			display: none;
		}
	</style> 
{% endfor %}
</div>

</div>

 {% endif %}

{% endblock %}

website/plataforma/templates/plataforma/topic_content.html
{% extends 'blog/base.html' %}


{% block content %}

 <nav class="" aria-label="breadcrumb">
         <ol class="breadcrumb">
            <li class="breadcrumb-item"><a  href="{% url 'index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'plataforma:plataforma_index' %}">Plataforma</a></li>
            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'plataforma:course_content' topic.category.course.id topic.category.course.link %}">{{topic.category.course.course_title|title}}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{topic.topic_title|title}}</li>
        </ol>
 </nav>

<div class="container">



<h1>{{topic.topic_title|title}}</h1>
<p>{{topic.content|safe}}</p>


<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Dúvidas, perguntas ou comentários?</h5>
        <p class="card-text">Comente abaixo.</p>
        <a href="#disqus_thread" class="btn btn-primary">Comentar</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Teste o seu conhecimento no assunto.</h5>
        <p class="card-text">Click no botão abaixo para ir ao questionário.</p>
        <a href="{% url 'plataforma:quiz' topic.id topic.link %}" class="btn btn-primary">Ir para o questionário</a>
      </div>
    </div>
  </div>
</div>


<div id="disqus_thread"></div>
<script>
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { 
var d = document, s = d.createElement('script');
s.src = 'https://zerotoheroenglish.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>

{% endblock %}

website/plataforma/templates/plataforma/user_page.html
{% extends 'blog/base.html' %}


{% block content %}

 <nav class="" aria-label="breadcrumb">
         <ol class="breadcrumb">
            <li class="breadcrumb-item"><a  href="{% url 'index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'plataforma:plataforma_index' %}">Plataforma</a></li>
            <li class="breadcrumb-item active" aria-current="page">Página do Usuário</li>
            
        </ol>
 </nav>


<div class="container">

{% if user.is_active %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Olá {{user.username}}</h1>
    <p class="lead">Nessa página você recebe os seus materiais particulares.</p>     
  </div>
</div>


<div class="card">
  <div class="card-header">
    Materiais Particulares
  </div>
  <div class="card-body">
    
    <p class="card-text">{{user.profile.releases|safe}}</p>
  
  </div>
</div>
 


{% endif %}


</div>




{% endblock %}

website/plataforma/templates/plataforma/word_list.html
{% extends 'blog/base.html' %}

{% block content %}
 <nav class="" aria-label="breadcrumb">
         <ol class="breadcrumb">
            <li class="breadcrumb-item"><a  href="{% url 'index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'plataforma:plataforma_index' %}">Plataforma</a></li>
            <li class="breadcrumb-item active" aria-current="page">Lista de palavras</li>
           </ol>
 </nav>


<div class="container">

	<div class="jumbotron jumbotron-fluid">
  		<div class="container">
    		<h1 class="display-4">Lista de Palavras</h1>
    		<p class="lead">Estude um grupo de palavras por dia. Faça frases, textos, use em seus vídeos, etc. Isso vai te ajudar muito a aprender inglês.</p>
    	</div>
</div>
{% for word_list in word_lists%}

<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne">
          {{word_list.list_name|safe}} - {{word_list.list_date}}
        </button>
      </h5>
    </div>

    <div id="collapse{{forloop.counter}}" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
        {{word_list.list_content|safe}}
      </div>
    </div>
  </div>  
</div>


{% endfor %}

</div>
{% endblock %}